# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yolo_serving.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'yolo_serving.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12yolo_serving.proto\x12\x0cyolo_serving\"\x83\x01\n\x0b\x42oundingBox\x12\r\n\x05y_min\x18\x01 \x01(\x02\x12\r\n\x05x_min\x18\x02 \x01(\x02\x12\r\n\x05y_max\x18\x03 \x01(\x02\x12\r\n\x05x_max\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x06 \x01(\x05\x12\x12\n\nclass_name\x18\x07 \x01(\t\"V\n\x0bYoloRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x1c\n\x14\x63onfidence_threshold\x18\x02 \x01(\x02\x12\x15\n\riou_threshold\x18\x03 \x01(\x02\"8\n\x0cYoloResponse\x12(\n\x05\x62oxes\x18\x01 \x03(\x0b\x32\x19.yolo_serving.BoundingBox\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xa7\x01\n\x13HealthCheckResponse\x12?\n\x06status\x18\x01 \x01(\x0e\x32/.yolo_serving.HealthCheckResponse.ServingStatus\"O\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03\x32\xa3\x01\n\x0bYoloService\x12@\n\x07Predict\x12\x19.yolo_serving.YoloRequest\x1a\x1a.yolo_serving.YoloResponse\x12R\n\x0b\x43heckHealth\x12 .yolo_serving.HealthCheckRequest\x1a!.yolo_serving.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolo_serving_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOUNDINGBOX']._serialized_start=37
  _globals['_BOUNDINGBOX']._serialized_end=168
  _globals['_YOLOREQUEST']._serialized_start=170
  _globals['_YOLOREQUEST']._serialized_end=256
  _globals['_YOLORESPONSE']._serialized_start=258
  _globals['_YOLORESPONSE']._serialized_end=314
  _globals['_HEALTHCHECKREQUEST']._serialized_start=316
  _globals['_HEALTHCHECKREQUEST']._serialized_end=353
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=356
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=523
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=444
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=523
  _globals['_YOLOSERVICE']._serialized_start=526
  _globals['_YOLOSERVICE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
